### ISSUE TITLE
Key error:'BB'

### ISSUE THREAD

**Issue by WillPPK** [owenvickery/cg2at#13]
Hi Owen or Phill,

I have been trying to CG2AT a protein in DLPC and this error came up. It's a direct mapping from martini2.2 to charmm36-2020 and this seems to be the issue. Can you point me to the right direction please?

Traceback (most recent call last)::  0.0 %                                                          
  File "/sansom/s133/trin2642/anaconda3/bin/cg2at", line 75, in <module>
    read_in.fix_pbc(box_vec_initial, g_var.box_vec, box_shift)
  File "/sansom/s133/trin2642/anaconda3/pkgs/cg2at-2021.09.23-0/info/recipe/database/bin/read_in.py", line 176, in fix_pbc
    BB_pre = g_var.cg_residues[residue_type][residue+connection][con_info['Con_Bd'][con_val]]['coord']
KeyError: 'BB'

Best wishes

Will

**Comment by WillPPK** [comment]
The issue has been solved. PyMOL has reordered the atom name so if the CG file is not in the correct order with BB SC1 SC2, this order will be flagged
